export const Topics = {

JOB_CREATED:"JOB_CREATED",

JOB_APPLIED:"JOB_APPLIED",

MESSAGE_SENT:"MESSAGE_SENT",

PAYMENT_CREATED:"PAYMENT_CREATED",

PAYMENT_RELEASED:"PAYMENT_RELEASED",

USER_REGISTERED:"USER_REGISTERED",

INVESTMENT_CREATED:"INVESTMENT_CREATED",

NOTIFICATION_CREATED:"NOTIFICATION_CREATED"

};
